In [44]:
import pandas as pd
df = pd.read_spss("Data/emotion2.sav")
df

                      group  emotion
0   научно-популярный фильм     31.0
1   научно-популярный фильм     24.0
2   научно-популярный фильм     36.0
3   научно-популярный фильм     37.0
4   научно-популярный фильм     37.0
5   научно-популярный фильм     36.0
6   научно-популярный фильм     37.0
7   научно-популярный фильм     34.0
8   научно-популярный фильм     33.0
9   научно-популярный фильм     35.0
10     лирическая зарисовка     33.0
11     лирическая зарисовка     26.0
12     лирическая зарисовка     38.0
13     лирическая зарисовка     39.0
14     лирическая зарисовка     39.0
15     лирическая зарисовка     38.0
16     лирическая зарисовка     39.0
17     лирическая зарисовка     36.0
18     лирическая зарисовка     35.0
19     лирическая зарисовка     37.0
20    криминальный репортаж     29.0
21    криминальный репортаж     22.0
22    криминальный репортаж     34.0
23    криминальный репортаж     35.0
24    криминальный репортаж     35.0
25    криминальный репортаж     34.0
26    криминальный репортаж     35.0
27    криминальный репортаж     32.0
28    криминальный репортаж     31.0
29    криминальный репортаж     33.0

In [46]:
mean = df.groupby('group').emotion.mean()
mean

/tmp/ipykernel_980/208648911.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean = df.groupby('group').emotion.mean()

group
криминальный репортаж      32.0
лирическая зарисовка       36.0
научно-популярный фильм    34.0
Name: emotion, dtype: float64